### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CAF-ID** [fawwaz37/nodejs-restapi#4]
/data/data/com.termux/files/home/nodejs-restapi/node_modules/express-recaptcha/dist/v2.js:23
            throw new Error('site_key is required');
            ^

Error: site_key is required
    at new RecaptchaV2 (/data/data/com.termux/files/home/nodejs-restapi/node_modules/express-recaptcha/dist/v2.js:23:19)
    at Object.<anonymous> (/data/data/com.termux/files/home/nodejs-restapi/routes/users.js:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/nodejs-restapi/app.js:13:21)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.8.0

**Comment by fawwaz37** [comment]
https://www.google.com/recaptcha/ > Go to Admin Console > Create reCAPTCHA v2 "I'm not a robot" > Submit

Key 1 = Site Key
Key 2 = Secret Key

Edit File settings.js in folder lib
https://github.com/fawwaz37/nodejs-restapi#editing-the-file
